// File generated from our OpenAPI spec by Stainless.

package ai.llamaindex.llamacloud.models.beta.sheets

import ai.llamaindex.llamacloud.core.JsonValue
import ai.llamaindex.llamacloud.core.jsonMapper
import ai.llamaindex.llamacloud.models.files.File
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SheetListPageResponseTest {

    @Test
    fun create() {
        val sheetListPageResponse =
            SheetListPageResponse.builder()
                .addItem(
                    SheetsJob.builder()
                        .id("id")
                        .configuration(
                            SheetsParsingConfig.builder()
                                .extractionRange("extraction_range")
                                .flattenHierarchicalTables(true)
                                .generateAdditionalMetadata(true)
                                .includeHiddenCells(true)
                                .addSheetName("string")
                                .specialization("specialization")
                                .tableMergeSensitivity(
                                    SheetsParsingConfig.TableMergeSensitivity.STRONG
                                )
                                .tier(SheetsParsingConfig.Tier.AGENTIC)
                                .useExperimentalProcessing(true)
                                .build()
                        )
                        .createdAt("created_at")
                        .fileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status(SheetsJob.Status.CANCELLED)
                        .updatedAt("updated_at")
                        .userId("user_id")
                        .config(
                            SheetsParsingConfig.builder()
                                .extractionRange("extraction_range")
                                .flattenHierarchicalTables(true)
                                .generateAdditionalMetadata(true)
                                .includeHiddenCells(true)
                                .addSheetName("string")
                                .specialization("specialization")
                                .tableMergeSensitivity(
                                    SheetsParsingConfig.TableMergeSensitivity.STRONG
                                )
                                .tier(SheetsParsingConfig.Tier.AGENTIC)
                                .useExperimentalProcessing(true)
                                .build()
                        )
                        .configurationId("configuration_id")
                        .addError("string")
                        .file(
                            File.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("x")
                                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .dataSourceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .externalFileId("external_file_id")
                                .fileSize(0L)
                                .fileType("x")
                                .lastModifiedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .permissionInfo(
                                    File.PermissionInfo.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to "bar")),
                                        )
                                        .build()
                                )
                                .purpose("purpose")
                                .resourceInfo(
                                    File.ResourceInfo.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to "bar")),
                                        )
                                        .build()
                                )
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .metadataStateTransitions(
                            SheetsJob.MetadataStateTransitions.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .parameters(
                            SheetsJob.Parameters.builder()
                                .addWebhookConfiguration(
                                    SheetsJob.Parameters.WebhookConfiguration.builder()
                                        .addWebhookEvent(
                                            SheetsJob.Parameters.WebhookConfiguration.WebhookEvent
                                                .PARSE_SUCCESS
                                        )
                                        .addWebhookEvent(
                                            SheetsJob.Parameters.WebhookConfiguration.WebhookEvent
                                                .PARSE_ERROR
                                        )
                                        .webhookHeaders(
                                            SheetsJob.Parameters.WebhookConfiguration.WebhookHeaders
                                                .builder()
                                                .putAdditionalProperty(
                                                    "Authorization",
                                                    JsonValue.from("Bearer sk-..."),
                                                )
                                                .build()
                                        )
                                        .webhookOutputFormat("json")
                                        .webhookSigningSecret("whsec_...")
                                        .webhookUrl("https://example.com/webhooks/llamacloud")
                                        .build()
                                )
                                .build()
                        )
                        .addRegion(
                            SheetsJob.Region.builder()
                                .location("location")
                                .regionType("region_type")
                                .sheetName("sheet_name")
                                .description("description")
                                .regionId("region_id")
                                .title("title")
                                .build()
                        )
                        .success(true)
                        .addWorksheetMetadata(
                            SheetsJob.WorksheetMetadata.builder()
                                .sheetName("sheet_name")
                                .description("description")
                                .title("title")
                                .build()
                        )
                        .build()
                )
                .nextPageToken("next_page_token")
                .totalSize(0L)
                .build()

        assertThat(sheetListPageResponse.items())
            .containsExactly(
                SheetsJob.builder()
                    .id("id")
                    .configuration(
                        SheetsParsingConfig.builder()
                            .extractionRange("extraction_range")
                            .flattenHierarchicalTables(true)
                            .generateAdditionalMetadata(true)
                            .includeHiddenCells(true)
                            .addSheetName("string")
                            .specialization("specialization")
                            .tableMergeSensitivity(SheetsParsingConfig.TableMergeSensitivity.STRONG)
                            .tier(SheetsParsingConfig.Tier.AGENTIC)
                            .useExperimentalProcessing(true)
                            .build()
                    )
                    .createdAt("created_at")
                    .fileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .status(SheetsJob.Status.CANCELLED)
                    .updatedAt("updated_at")
                    .userId("user_id")
                    .config(
                        SheetsParsingConfig.builder()
                            .extractionRange("extraction_range")
                            .flattenHierarchicalTables(true)
                            .generateAdditionalMetadata(true)
                            .includeHiddenCells(true)
                            .addSheetName("string")
                            .specialization("specialization")
                            .tableMergeSensitivity(SheetsParsingConfig.TableMergeSensitivity.STRONG)
                            .tier(SheetsParsingConfig.Tier.AGENTIC)
                            .useExperimentalProcessing(true)
                            .build()
                    )
                    .configurationId("configuration_id")
                    .addError("string")
                    .file(
                        File.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("x")
                            .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .dataSourceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .externalFileId("external_file_id")
                            .fileSize(0L)
                            .fileType("x")
                            .lastModifiedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .permissionInfo(
                                File.PermissionInfo.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf("foo" to "bar")),
                                    )
                                    .build()
                            )
                            .purpose("purpose")
                            .resourceInfo(
                                File.ResourceInfo.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf("foo" to "bar")),
                                    )
                                    .build()
                            )
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .metadataStateTransitions(
                        SheetsJob.MetadataStateTransitions.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .parameters(
                        SheetsJob.Parameters.builder()
                            .addWebhookConfiguration(
                                SheetsJob.Parameters.WebhookConfiguration.builder()
                                    .addWebhookEvent(
                                        SheetsJob.Parameters.WebhookConfiguration.WebhookEvent
                                            .PARSE_SUCCESS
                                    )
                                    .addWebhookEvent(
                                        SheetsJob.Parameters.WebhookConfiguration.WebhookEvent
                                            .PARSE_ERROR
                                    )
                                    .webhookHeaders(
                                        SheetsJob.Parameters.WebhookConfiguration.WebhookHeaders
                                            .builder()
                                            .putAdditionalProperty(
                                                "Authorization",
                                                JsonValue.from("Bearer sk-..."),
                                            )
                                            .build()
                                    )
                                    .webhookOutputFormat("json")
                                    .webhookSigningSecret("whsec_...")
                                    .webhookUrl("https://example.com/webhooks/llamacloud")
                                    .build()
                            )
                            .build()
                    )
                    .addRegion(
                        SheetsJob.Region.builder()
                            .location("location")
                            .regionType("region_type")
                            .sheetName("sheet_name")
                            .description("description")
                            .regionId("region_id")
                            .title("title")
                            .build()
                    )
                    .success(true)
                    .addWorksheetMetadata(
                        SheetsJob.WorksheetMetadata.builder()
                            .sheetName("sheet_name")
                            .description("description")
                            .title("title")
                            .build()
                    )
                    .build()
            )
        assertThat(sheetListPageResponse.nextPageToken()).contains("next_page_token")
        assertThat(sheetListPageResponse.totalSize()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val sheetListPageResponse =
            SheetListPageResponse.builder()
                .addItem(
                    SheetsJob.builder()
                        .id("id")
                        .configuration(
                            SheetsParsingConfig.builder()
                                .extractionRange("extraction_range")
                                .flattenHierarchicalTables(true)
                                .generateAdditionalMetadata(true)
                                .includeHiddenCells(true)
                                .addSheetName("string")
                                .specialization("specialization")
                                .tableMergeSensitivity(
                                    SheetsParsingConfig.TableMergeSensitivity.STRONG
                                )
                                .tier(SheetsParsingConfig.Tier.AGENTIC)
                                .useExperimentalProcessing(true)
                                .build()
                        )
                        .createdAt("created_at")
                        .fileId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status(SheetsJob.Status.CANCELLED)
                        .updatedAt("updated_at")
                        .userId("user_id")
                        .config(
                            SheetsParsingConfig.builder()
                                .extractionRange("extraction_range")
                                .flattenHierarchicalTables(true)
                                .generateAdditionalMetadata(true)
                                .includeHiddenCells(true)
                                .addSheetName("string")
                                .specialization("specialization")
                                .tableMergeSensitivity(
                                    SheetsParsingConfig.TableMergeSensitivity.STRONG
                                )
                                .tier(SheetsParsingConfig.Tier.AGENTIC)
                                .useExperimentalProcessing(true)
                                .build()
                        )
                        .configurationId("configuration_id")
                        .addError("string")
                        .file(
                            File.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("x")
                                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .dataSourceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .externalFileId("external_file_id")
                                .fileSize(0L)
                                .fileType("x")
                                .lastModifiedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .permissionInfo(
                                    File.PermissionInfo.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to "bar")),
                                        )
                                        .build()
                                )
                                .purpose("purpose")
                                .resourceInfo(
                                    File.ResourceInfo.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to "bar")),
                                        )
                                        .build()
                                )
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .metadataStateTransitions(
                            SheetsJob.MetadataStateTransitions.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .parameters(
                            SheetsJob.Parameters.builder()
                                .addWebhookConfiguration(
                                    SheetsJob.Parameters.WebhookConfiguration.builder()
                                        .addWebhookEvent(
                                            SheetsJob.Parameters.WebhookConfiguration.WebhookEvent
                                                .PARSE_SUCCESS
                                        )
                                        .addWebhookEvent(
                                            SheetsJob.Parameters.WebhookConfiguration.WebhookEvent
                                                .PARSE_ERROR
                                        )
                                        .webhookHeaders(
                                            SheetsJob.Parameters.WebhookConfiguration.WebhookHeaders
                                                .builder()
                                                .putAdditionalProperty(
                                                    "Authorization",
                                                    JsonValue.from("Bearer sk-..."),
                                                )
                                                .build()
                                        )
                                        .webhookOutputFormat("json")
                                        .webhookSigningSecret("whsec_...")
                                        .webhookUrl("https://example.com/webhooks/llamacloud")
                                        .build()
                                )
                                .build()
                        )
                        .addRegion(
                            SheetsJob.Region.builder()
                                .location("location")
                                .regionType("region_type")
                                .sheetName("sheet_name")
                                .description("description")
                                .regionId("region_id")
                                .title("title")
                                .build()
                        )
                        .success(true)
                        .addWorksheetMetadata(
                            SheetsJob.WorksheetMetadata.builder()
                                .sheetName("sheet_name")
                                .description("description")
                                .title("title")
                                .build()
                        )
                        .build()
                )
                .nextPageToken("next_page_token")
                .totalSize(0L)
                .build()

        val roundtrippedSheetListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(sheetListPageResponse),
                jacksonTypeRef<SheetListPageResponse>(),
            )

        assertThat(roundtrippedSheetListPageResponse).isEqualTo(sheetListPageResponse)
    }
}
