// File generated from our OpenAPI spec by Stainless.

package com.llamacloud_prod.api.models.configurations

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.llamacloud_prod.api.core.JsonValue
import com.llamacloud_prod.api.core.jsonMapper
import com.llamacloud_prod.api.models.parsing.ParsingLanguages
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ParseV2ParametersTest {

    @Test
    fun create() {
        val parseV2Parameters =
            ParseV2Parameters.builder()
                .tier(ParseV2Parameters.Tier.AGENTIC)
                .version(ParseV2Parameters.Version.LATEST)
                .agenticOptions(
                    ParseV2Parameters.AgenticOptions.builder().customPrompt("custom_prompt").build()
                )
                .clientName("client_name")
                .cropBox(
                    ParseV2Parameters.CropBox.builder()
                        .bottom(0.0)
                        .left(0.0)
                        .right(0.0)
                        .top(0.0)
                        .build()
                )
                .disableCache(true)
                .fastOptions(JsonValue.from(mapOf<String, Any>()))
                .inputOptions(
                    ParseV2Parameters.InputOptions.builder()
                        .html(
                            ParseV2Parameters.InputOptions.Html.builder()
                                .makeAllElementsVisible(true)
                                .removeFixedElements(true)
                                .removeNavigationElements(true)
                                .build()
                        )
                        .image(
                            ParseV2Parameters.InputOptions.Image.builder()
                                .cameraPhotoCorrection(true)
                                .build()
                        )
                        .pdf(JsonValue.from(mapOf<String, Any>()))
                        .presentation(
                            ParseV2Parameters.InputOptions.Presentation.builder()
                                .outOfBoundsContent(true)
                                .skipEmbeddedData(true)
                                .build()
                        )
                        .spreadsheet(
                            ParseV2Parameters.InputOptions.Spreadsheet.builder()
                                .detectSubTablesInSheets(true)
                                .forceFormulaComputationInSheets(true)
                                .includeHiddenSheets(true)
                                .build()
                        )
                        .build()
                )
                .outputOptions(
                    ParseV2Parameters.OutputOptions.builder()
                        .additionalOutputs(
                            listOf("stripped_md", "concatenated_stripped_txt", "word_bbox")
                        )
                        .extractPrintedPageNumber(true)
                        .granularBboxes(
                            listOf(
                                ParseV2Parameters.OutputOptions.GranularBbox.WORD,
                                ParseV2Parameters.OutputOptions.GranularBbox.LINE,
                                ParseV2Parameters.OutputOptions.GranularBbox.CELL,
                            )
                        )
                        .addImagesToSave(ParseV2Parameters.OutputOptions.ImagesToSave.EMBEDDED)
                        .markdown(
                            ParseV2Parameters.OutputOptions.Markdown.builder()
                                .annotateLinks(true)
                                .inlineImages(true)
                                .tables(
                                    ParseV2Parameters.OutputOptions.Markdown.Tables.builder()
                                        .compactMarkdownTables(true)
                                        .markdownTableMultilineSeparator(
                                            "markdown_table_multiline_separator"
                                        )
                                        .mergeContinuedTables(true)
                                        .outputTablesAsMarkdown(true)
                                        .build()
                                )
                                .build()
                        )
                        .spatialText(
                            ParseV2Parameters.OutputOptions.SpatialText.builder()
                                .doNotUnrollColumns(true)
                                .preserveLayoutAlignmentAcrossPages(true)
                                .preserveVerySmallText(true)
                                .build()
                        )
                        .tablesAsSpreadsheet(
                            ParseV2Parameters.OutputOptions.TablesAsSpreadsheet.builder()
                                .enable(true)
                                .guessSheetName(true)
                                .build()
                        )
                        .build()
                )
                .pageRanges(
                    ParseV2Parameters.PageRanges.builder()
                        .maxPages(1L)
                        .targetPages("target_pages")
                        .build()
                )
                .processingControl(
                    ParseV2Parameters.ProcessingControl.builder()
                        .jobFailureConditions(
                            ParseV2Parameters.ProcessingControl.JobFailureConditions.builder()
                                .allowedPageFailureRatio(1.0)
                                .failOnBuggyFont(true)
                                .failOnImageExtractionError(true)
                                .failOnImageOcrError(true)
                                .failOnMarkdownReconstructionError(true)
                                .build()
                        )
                        .timeouts(
                            ParseV2Parameters.ProcessingControl.Timeouts.builder()
                                .baseInSeconds(1L)
                                .extraTimePerPageInSeconds(1L)
                                .build()
                        )
                        .build()
                )
                .processingOptions(
                    ParseV2Parameters.ProcessingOptions.builder()
                        .aggressiveTableExtraction(true)
                        .addAutoModeConfiguration(
                            ParseV2Parameters.ProcessingOptions.AutoModeConfiguration.builder()
                                .parsingConf(
                                    ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                        .ParsingConf
                                        .builder()
                                        .adaptiveLongTable(true)
                                        .aggressiveTableExtraction(true)
                                        .cropBox(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .CropBox
                                                .builder()
                                                .bottom(0.0)
                                                .left(0.0)
                                                .right(0.0)
                                                .top(0.0)
                                                .build()
                                        )
                                        .customPrompt("custom_prompt")
                                        .extractLayout(true)
                                        .highResOcr(true)
                                        .ignore(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Ignore
                                                .builder()
                                                .ignoreDiagonalText(true)
                                                .ignoreHiddenText(true)
                                                .build()
                                        )
                                        .language("language")
                                        .outlinedTableExtraction(true)
                                        .presentation(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Presentation
                                                .builder()
                                                .outOfBoundsContent(true)
                                                .skipEmbeddedData(true)
                                                .build()
                                        )
                                        .spatialText(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .SpatialText
                                                .builder()
                                                .doNotUnrollColumns(true)
                                                .preserveLayoutAlignmentAcrossPages(true)
                                                .preserveVerySmallText(true)
                                                .build()
                                        )
                                        .specializedChartParsing(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .SpecializedChartParsing
                                                .AGENTIC
                                        )
                                        .tier(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Tier
                                                .AGENTIC
                                        )
                                        .version(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Version
                                                .LATEST
                                        )
                                        .build()
                                )
                                .filenameMatchGlob("*.txt")
                                .addFilenameMatchGlobList("string")
                                .filenameRegexp("filename_regexp")
                                .filenameRegexpMode("filename_regexp_mode")
                                .fullPageImageInPage(true)
                                .fullPageImageInPageThreshold(0.0)
                                .imageInPage(true)
                                .layoutElementInPage("layout_element_in_page")
                                .layoutElementInPageConfidenceThreshold(0.0)
                                .pageContainsAtLeastNCharts(0L)
                                .pageContainsAtLeastNImages(0L)
                                .pageContainsAtLeastNLayoutElements(0L)
                                .pageContainsAtLeastNLines(0L)
                                .pageContainsAtLeastNLinks(0L)
                                .pageContainsAtLeastNNumbers(0L)
                                .pageContainsAtLeastNPercentNumbers(0L)
                                .pageContainsAtLeastNTables(0L)
                                .pageContainsAtLeastNWords(0L)
                                .pageContainsAtMostNCharts(0L)
                                .pageContainsAtMostNImages(0L)
                                .pageContainsAtMostNLayoutElements(0L)
                                .pageContainsAtMostNLines(0L)
                                .pageContainsAtMostNLinks(0L)
                                .pageContainsAtMostNNumbers(0L)
                                .pageContainsAtMostNPercentNumbers(0L)
                                .pageContainsAtMostNTables(0L)
                                .pageContainsAtMostNWords(0L)
                                .pageLongerThanNChars(0L)
                                .pageMdError(true)
                                .pageShorterThanNChars(0L)
                                .regexpInPage("regexp_in_page")
                                .regexpInPageMode("regexp_in_page_mode")
                                .tableInPage(true)
                                .textInPage("text_in_page")
                                .triggerMode("trigger_mode")
                                .build()
                        )
                        .costOptimizer(
                            ParseV2Parameters.ProcessingOptions.CostOptimizer.builder()
                                .enable(true)
                                .build()
                        )
                        .disableHeuristics(true)
                        .forms(ParseV2Parameters.ProcessingOptions.Forms.ENRICH)
                        .ignore(
                            ParseV2Parameters.ProcessingOptions.Ignore.builder()
                                .ignoreDiagonalText(true)
                                .ignoreHiddenText(true)
                                .ignoreTextInImage(true)
                                .build()
                        )
                        .ocrParameters(
                            ParseV2Parameters.ProcessingOptions.OcrParameters.builder()
                                .addLanguage(ParsingLanguages.ABQ)
                                .build()
                        )
                        .specializedChartParsing(
                            ParseV2Parameters.ProcessingOptions.SpecializedChartParsing.AGENTIC
                        )
                        .build()
                )
                .addWebhookConfigurationId("whc-...")
                .addWebhookConfigurationId("whc-...")
                .addWebhookConfiguration(
                    ParseV2Parameters.WebhookConfiguration.builder()
                        .addWebhookEvent("parse.success")
                        .addWebhookEvent("parse.error")
                        .webhookHeaders(
                            ParseV2Parameters.WebhookConfiguration.WebhookHeaders.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .webhookOutputFormat(
                            ParseV2Parameters.WebhookConfiguration.WebhookOutputFormat.JSON
                        )
                        .webhookSigningSecret("webhook_signing_secret")
                        .webhookUrl("https:")
                        .build()
                )
                .build()

        assertThat(parseV2Parameters.tier()).isEqualTo(ParseV2Parameters.Tier.AGENTIC)
        assertThat(parseV2Parameters.version()).isEqualTo(ParseV2Parameters.Version.LATEST)
        assertThat(parseV2Parameters.agenticOptions())
            .contains(
                ParseV2Parameters.AgenticOptions.builder().customPrompt("custom_prompt").build()
            )
        assertThat(parseV2Parameters.clientName()).contains("client_name")
        assertThat(parseV2Parameters.cropBox())
            .contains(
                ParseV2Parameters.CropBox.builder()
                    .bottom(0.0)
                    .left(0.0)
                    .right(0.0)
                    .top(0.0)
                    .build()
            )
        assertThat(parseV2Parameters.disableCache()).contains(true)
        assertThat(parseV2Parameters._fastOptions()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(parseV2Parameters.inputOptions())
            .contains(
                ParseV2Parameters.InputOptions.builder()
                    .html(
                        ParseV2Parameters.InputOptions.Html.builder()
                            .makeAllElementsVisible(true)
                            .removeFixedElements(true)
                            .removeNavigationElements(true)
                            .build()
                    )
                    .image(
                        ParseV2Parameters.InputOptions.Image.builder()
                            .cameraPhotoCorrection(true)
                            .build()
                    )
                    .pdf(JsonValue.from(mapOf<String, Any>()))
                    .presentation(
                        ParseV2Parameters.InputOptions.Presentation.builder()
                            .outOfBoundsContent(true)
                            .skipEmbeddedData(true)
                            .build()
                    )
                    .spreadsheet(
                        ParseV2Parameters.InputOptions.Spreadsheet.builder()
                            .detectSubTablesInSheets(true)
                            .forceFormulaComputationInSheets(true)
                            .includeHiddenSheets(true)
                            .build()
                    )
                    .build()
            )
        assertThat(parseV2Parameters.outputOptions())
            .contains(
                ParseV2Parameters.OutputOptions.builder()
                    .additionalOutputs(
                        listOf("stripped_md", "concatenated_stripped_txt", "word_bbox")
                    )
                    .extractPrintedPageNumber(true)
                    .granularBboxes(
                        listOf(
                            ParseV2Parameters.OutputOptions.GranularBbox.WORD,
                            ParseV2Parameters.OutputOptions.GranularBbox.LINE,
                            ParseV2Parameters.OutputOptions.GranularBbox.CELL,
                        )
                    )
                    .addImagesToSave(ParseV2Parameters.OutputOptions.ImagesToSave.EMBEDDED)
                    .markdown(
                        ParseV2Parameters.OutputOptions.Markdown.builder()
                            .annotateLinks(true)
                            .inlineImages(true)
                            .tables(
                                ParseV2Parameters.OutputOptions.Markdown.Tables.builder()
                                    .compactMarkdownTables(true)
                                    .markdownTableMultilineSeparator(
                                        "markdown_table_multiline_separator"
                                    )
                                    .mergeContinuedTables(true)
                                    .outputTablesAsMarkdown(true)
                                    .build()
                            )
                            .build()
                    )
                    .spatialText(
                        ParseV2Parameters.OutputOptions.SpatialText.builder()
                            .doNotUnrollColumns(true)
                            .preserveLayoutAlignmentAcrossPages(true)
                            .preserveVerySmallText(true)
                            .build()
                    )
                    .tablesAsSpreadsheet(
                        ParseV2Parameters.OutputOptions.TablesAsSpreadsheet.builder()
                            .enable(true)
                            .guessSheetName(true)
                            .build()
                    )
                    .build()
            )
        assertThat(parseV2Parameters.pageRanges())
            .contains(
                ParseV2Parameters.PageRanges.builder()
                    .maxPages(1L)
                    .targetPages("target_pages")
                    .build()
            )
        assertThat(parseV2Parameters.processingControl())
            .contains(
                ParseV2Parameters.ProcessingControl.builder()
                    .jobFailureConditions(
                        ParseV2Parameters.ProcessingControl.JobFailureConditions.builder()
                            .allowedPageFailureRatio(1.0)
                            .failOnBuggyFont(true)
                            .failOnImageExtractionError(true)
                            .failOnImageOcrError(true)
                            .failOnMarkdownReconstructionError(true)
                            .build()
                    )
                    .timeouts(
                        ParseV2Parameters.ProcessingControl.Timeouts.builder()
                            .baseInSeconds(1L)
                            .extraTimePerPageInSeconds(1L)
                            .build()
                    )
                    .build()
            )
        assertThat(parseV2Parameters.processingOptions())
            .contains(
                ParseV2Parameters.ProcessingOptions.builder()
                    .aggressiveTableExtraction(true)
                    .addAutoModeConfiguration(
                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration.builder()
                            .parsingConf(
                                ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                    .ParsingConf
                                    .builder()
                                    .adaptiveLongTable(true)
                                    .aggressiveTableExtraction(true)
                                    .cropBox(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .CropBox
                                            .builder()
                                            .bottom(0.0)
                                            .left(0.0)
                                            .right(0.0)
                                            .top(0.0)
                                            .build()
                                    )
                                    .customPrompt("custom_prompt")
                                    .extractLayout(true)
                                    .highResOcr(true)
                                    .ignore(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .Ignore
                                            .builder()
                                            .ignoreDiagonalText(true)
                                            .ignoreHiddenText(true)
                                            .build()
                                    )
                                    .language("language")
                                    .outlinedTableExtraction(true)
                                    .presentation(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .Presentation
                                            .builder()
                                            .outOfBoundsContent(true)
                                            .skipEmbeddedData(true)
                                            .build()
                                    )
                                    .spatialText(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .SpatialText
                                            .builder()
                                            .doNotUnrollColumns(true)
                                            .preserveLayoutAlignmentAcrossPages(true)
                                            .preserveVerySmallText(true)
                                            .build()
                                    )
                                    .specializedChartParsing(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .SpecializedChartParsing
                                            .AGENTIC
                                    )
                                    .tier(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .Tier
                                            .AGENTIC
                                    )
                                    .version(
                                        ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                            .ParsingConf
                                            .Version
                                            .LATEST
                                    )
                                    .build()
                            )
                            .filenameMatchGlob("*.txt")
                            .addFilenameMatchGlobList("string")
                            .filenameRegexp("filename_regexp")
                            .filenameRegexpMode("filename_regexp_mode")
                            .fullPageImageInPage(true)
                            .fullPageImageInPageThreshold(0.0)
                            .imageInPage(true)
                            .layoutElementInPage("layout_element_in_page")
                            .layoutElementInPageConfidenceThreshold(0.0)
                            .pageContainsAtLeastNCharts(0L)
                            .pageContainsAtLeastNImages(0L)
                            .pageContainsAtLeastNLayoutElements(0L)
                            .pageContainsAtLeastNLines(0L)
                            .pageContainsAtLeastNLinks(0L)
                            .pageContainsAtLeastNNumbers(0L)
                            .pageContainsAtLeastNPercentNumbers(0L)
                            .pageContainsAtLeastNTables(0L)
                            .pageContainsAtLeastNWords(0L)
                            .pageContainsAtMostNCharts(0L)
                            .pageContainsAtMostNImages(0L)
                            .pageContainsAtMostNLayoutElements(0L)
                            .pageContainsAtMostNLines(0L)
                            .pageContainsAtMostNLinks(0L)
                            .pageContainsAtMostNNumbers(0L)
                            .pageContainsAtMostNPercentNumbers(0L)
                            .pageContainsAtMostNTables(0L)
                            .pageContainsAtMostNWords(0L)
                            .pageLongerThanNChars(0L)
                            .pageMdError(true)
                            .pageShorterThanNChars(0L)
                            .regexpInPage("regexp_in_page")
                            .regexpInPageMode("regexp_in_page_mode")
                            .tableInPage(true)
                            .textInPage("text_in_page")
                            .triggerMode("trigger_mode")
                            .build()
                    )
                    .costOptimizer(
                        ParseV2Parameters.ProcessingOptions.CostOptimizer.builder()
                            .enable(true)
                            .build()
                    )
                    .disableHeuristics(true)
                    .forms(ParseV2Parameters.ProcessingOptions.Forms.ENRICH)
                    .ignore(
                        ParseV2Parameters.ProcessingOptions.Ignore.builder()
                            .ignoreDiagonalText(true)
                            .ignoreHiddenText(true)
                            .ignoreTextInImage(true)
                            .build()
                    )
                    .ocrParameters(
                        ParseV2Parameters.ProcessingOptions.OcrParameters.builder()
                            .addLanguage(ParsingLanguages.ABQ)
                            .build()
                    )
                    .specializedChartParsing(
                        ParseV2Parameters.ProcessingOptions.SpecializedChartParsing.AGENTIC
                    )
                    .build()
            )
        assertThat(parseV2Parameters.webhookConfigurationIds().getOrNull())
            .containsExactly("whc-...", "whc-...")
        assertThat(parseV2Parameters.webhookConfigurations().getOrNull())
            .containsExactly(
                ParseV2Parameters.WebhookConfiguration.builder()
                    .addWebhookEvent("parse.success")
                    .addWebhookEvent("parse.error")
                    .webhookHeaders(
                        ParseV2Parameters.WebhookConfiguration.WebhookHeaders.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .webhookOutputFormat(
                        ParseV2Parameters.WebhookConfiguration.WebhookOutputFormat.JSON
                    )
                    .webhookSigningSecret("webhook_signing_secret")
                    .webhookUrl("https:")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val parseV2Parameters =
            ParseV2Parameters.builder()
                .tier(ParseV2Parameters.Tier.AGENTIC)
                .version(ParseV2Parameters.Version.LATEST)
                .agenticOptions(
                    ParseV2Parameters.AgenticOptions.builder().customPrompt("custom_prompt").build()
                )
                .clientName("client_name")
                .cropBox(
                    ParseV2Parameters.CropBox.builder()
                        .bottom(0.0)
                        .left(0.0)
                        .right(0.0)
                        .top(0.0)
                        .build()
                )
                .disableCache(true)
                .fastOptions(JsonValue.from(mapOf<String, Any>()))
                .inputOptions(
                    ParseV2Parameters.InputOptions.builder()
                        .html(
                            ParseV2Parameters.InputOptions.Html.builder()
                                .makeAllElementsVisible(true)
                                .removeFixedElements(true)
                                .removeNavigationElements(true)
                                .build()
                        )
                        .image(
                            ParseV2Parameters.InputOptions.Image.builder()
                                .cameraPhotoCorrection(true)
                                .build()
                        )
                        .pdf(JsonValue.from(mapOf<String, Any>()))
                        .presentation(
                            ParseV2Parameters.InputOptions.Presentation.builder()
                                .outOfBoundsContent(true)
                                .skipEmbeddedData(true)
                                .build()
                        )
                        .spreadsheet(
                            ParseV2Parameters.InputOptions.Spreadsheet.builder()
                                .detectSubTablesInSheets(true)
                                .forceFormulaComputationInSheets(true)
                                .includeHiddenSheets(true)
                                .build()
                        )
                        .build()
                )
                .outputOptions(
                    ParseV2Parameters.OutputOptions.builder()
                        .additionalOutputs(
                            listOf("stripped_md", "concatenated_stripped_txt", "word_bbox")
                        )
                        .extractPrintedPageNumber(true)
                        .granularBboxes(
                            listOf(
                                ParseV2Parameters.OutputOptions.GranularBbox.WORD,
                                ParseV2Parameters.OutputOptions.GranularBbox.LINE,
                                ParseV2Parameters.OutputOptions.GranularBbox.CELL,
                            )
                        )
                        .addImagesToSave(ParseV2Parameters.OutputOptions.ImagesToSave.EMBEDDED)
                        .markdown(
                            ParseV2Parameters.OutputOptions.Markdown.builder()
                                .annotateLinks(true)
                                .inlineImages(true)
                                .tables(
                                    ParseV2Parameters.OutputOptions.Markdown.Tables.builder()
                                        .compactMarkdownTables(true)
                                        .markdownTableMultilineSeparator(
                                            "markdown_table_multiline_separator"
                                        )
                                        .mergeContinuedTables(true)
                                        .outputTablesAsMarkdown(true)
                                        .build()
                                )
                                .build()
                        )
                        .spatialText(
                            ParseV2Parameters.OutputOptions.SpatialText.builder()
                                .doNotUnrollColumns(true)
                                .preserveLayoutAlignmentAcrossPages(true)
                                .preserveVerySmallText(true)
                                .build()
                        )
                        .tablesAsSpreadsheet(
                            ParseV2Parameters.OutputOptions.TablesAsSpreadsheet.builder()
                                .enable(true)
                                .guessSheetName(true)
                                .build()
                        )
                        .build()
                )
                .pageRanges(
                    ParseV2Parameters.PageRanges.builder()
                        .maxPages(1L)
                        .targetPages("target_pages")
                        .build()
                )
                .processingControl(
                    ParseV2Parameters.ProcessingControl.builder()
                        .jobFailureConditions(
                            ParseV2Parameters.ProcessingControl.JobFailureConditions.builder()
                                .allowedPageFailureRatio(1.0)
                                .failOnBuggyFont(true)
                                .failOnImageExtractionError(true)
                                .failOnImageOcrError(true)
                                .failOnMarkdownReconstructionError(true)
                                .build()
                        )
                        .timeouts(
                            ParseV2Parameters.ProcessingControl.Timeouts.builder()
                                .baseInSeconds(1L)
                                .extraTimePerPageInSeconds(1L)
                                .build()
                        )
                        .build()
                )
                .processingOptions(
                    ParseV2Parameters.ProcessingOptions.builder()
                        .aggressiveTableExtraction(true)
                        .addAutoModeConfiguration(
                            ParseV2Parameters.ProcessingOptions.AutoModeConfiguration.builder()
                                .parsingConf(
                                    ParseV2Parameters.ProcessingOptions.AutoModeConfiguration
                                        .ParsingConf
                                        .builder()
                                        .adaptiveLongTable(true)
                                        .aggressiveTableExtraction(true)
                                        .cropBox(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .CropBox
                                                .builder()
                                                .bottom(0.0)
                                                .left(0.0)
                                                .right(0.0)
                                                .top(0.0)
                                                .build()
                                        )
                                        .customPrompt("custom_prompt")
                                        .extractLayout(true)
                                        .highResOcr(true)
                                        .ignore(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Ignore
                                                .builder()
                                                .ignoreDiagonalText(true)
                                                .ignoreHiddenText(true)
                                                .build()
                                        )
                                        .language("language")
                                        .outlinedTableExtraction(true)
                                        .presentation(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Presentation
                                                .builder()
                                                .outOfBoundsContent(true)
                                                .skipEmbeddedData(true)
                                                .build()
                                        )
                                        .spatialText(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .SpatialText
                                                .builder()
                                                .doNotUnrollColumns(true)
                                                .preserveLayoutAlignmentAcrossPages(true)
                                                .preserveVerySmallText(true)
                                                .build()
                                        )
                                        .specializedChartParsing(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .SpecializedChartParsing
                                                .AGENTIC
                                        )
                                        .tier(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Tier
                                                .AGENTIC
                                        )
                                        .version(
                                            ParseV2Parameters.ProcessingOptions
                                                .AutoModeConfiguration
                                                .ParsingConf
                                                .Version
                                                .LATEST
                                        )
                                        .build()
                                )
                                .filenameMatchGlob("*.txt")
                                .addFilenameMatchGlobList("string")
                                .filenameRegexp("filename_regexp")
                                .filenameRegexpMode("filename_regexp_mode")
                                .fullPageImageInPage(true)
                                .fullPageImageInPageThreshold(0.0)
                                .imageInPage(true)
                                .layoutElementInPage("layout_element_in_page")
                                .layoutElementInPageConfidenceThreshold(0.0)
                                .pageContainsAtLeastNCharts(0L)
                                .pageContainsAtLeastNImages(0L)
                                .pageContainsAtLeastNLayoutElements(0L)
                                .pageContainsAtLeastNLines(0L)
                                .pageContainsAtLeastNLinks(0L)
                                .pageContainsAtLeastNNumbers(0L)
                                .pageContainsAtLeastNPercentNumbers(0L)
                                .pageContainsAtLeastNTables(0L)
                                .pageContainsAtLeastNWords(0L)
                                .pageContainsAtMostNCharts(0L)
                                .pageContainsAtMostNImages(0L)
                                .pageContainsAtMostNLayoutElements(0L)
                                .pageContainsAtMostNLines(0L)
                                .pageContainsAtMostNLinks(0L)
                                .pageContainsAtMostNNumbers(0L)
                                .pageContainsAtMostNPercentNumbers(0L)
                                .pageContainsAtMostNTables(0L)
                                .pageContainsAtMostNWords(0L)
                                .pageLongerThanNChars(0L)
                                .pageMdError(true)
                                .pageShorterThanNChars(0L)
                                .regexpInPage("regexp_in_page")
                                .regexpInPageMode("regexp_in_page_mode")
                                .tableInPage(true)
                                .textInPage("text_in_page")
                                .triggerMode("trigger_mode")
                                .build()
                        )
                        .costOptimizer(
                            ParseV2Parameters.ProcessingOptions.CostOptimizer.builder()
                                .enable(true)
                                .build()
                        )
                        .disableHeuristics(true)
                        .forms(ParseV2Parameters.ProcessingOptions.Forms.ENRICH)
                        .ignore(
                            ParseV2Parameters.ProcessingOptions.Ignore.builder()
                                .ignoreDiagonalText(true)
                                .ignoreHiddenText(true)
                                .ignoreTextInImage(true)
                                .build()
                        )
                        .ocrParameters(
                            ParseV2Parameters.ProcessingOptions.OcrParameters.builder()
                                .addLanguage(ParsingLanguages.ABQ)
                                .build()
                        )
                        .specializedChartParsing(
                            ParseV2Parameters.ProcessingOptions.SpecializedChartParsing.AGENTIC
                        )
                        .build()
                )
                .addWebhookConfigurationId("whc-...")
                .addWebhookConfigurationId("whc-...")
                .addWebhookConfiguration(
                    ParseV2Parameters.WebhookConfiguration.builder()
                        .addWebhookEvent("parse.success")
                        .addWebhookEvent("parse.error")
                        .webhookHeaders(
                            ParseV2Parameters.WebhookConfiguration.WebhookHeaders.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .webhookOutputFormat(
                            ParseV2Parameters.WebhookConfiguration.WebhookOutputFormat.JSON
                        )
                        .webhookSigningSecret("webhook_signing_secret")
                        .webhookUrl("https:")
                        .build()
                )
                .build()

        val roundtrippedParseV2Parameters =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(parseV2Parameters),
                jacksonTypeRef<ParseV2Parameters>(),
            )

        assertThat(roundtrippedParseV2Parameters).isEqualTo(parseV2Parameters)
    }
}
