// File generated from our OpenAPI spec by Stainless.

package ai.llamaindex.llamacloud.models.alpha.verify

import ai.llamaindex.llamacloud.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class VerifyListResponseTest {

    @Test
    fun create() {
        val verifyListResponse =
            VerifyListResponse.builder()
                .id("id")
                .configuration(
                    VerifyListResponse.Configuration.builder()
                        .targetPages("1,3,5-7")
                        .tier(VerifyListResponse.Configuration.Tier.AGENTIC)
                        .build()
                )
                .documentInputType(VerifyListResponse.DocumentInputType.FILE_ID)
                .fileInput("file_input")
                .projectId("project_id")
                .status(VerifyListResponse.Status.CANCELLED)
                .userId("user_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .errorMessage("error_message")
                .result(
                    VerifyListResponse.Result.builder()
                        .detectorVersion("detector_version")
                        .overallScore(0.0)
                        .verdict(VerifyListResponse.Result.Verdict.AUTHENTIC)
                        .compositeScores(
                            VerifyListResponse.Result.CompositeScores.builder()
                                .aiGenerated(
                                    VerifyListResponse.Result.CompositeScores.AiGenerated.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentCoherence(
                                    VerifyListResponse.Result.CompositeScores.DocumentCoherence
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentMetadata(
                                    VerifyListResponse.Result.CompositeScores.DocumentMetadata
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .knownFraud(
                                    VerifyListResponse.Result.CompositeScores.KnownFraud.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .manuallyEdited(
                                    VerifyListResponse.Result.CompositeScores.ManuallyEdited
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .recapture(
                                    VerifyListResponse.Result.CompositeScores.Recapture.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .confidence(0.0)
                        .error("error")
                        .pageCount(1L)
                        .addPageDimension(
                            VerifyListResponse.Result.PageDimension.builder()
                                .height(0L)
                                .page(0L)
                                .width(0L)
                                .build()
                        )
                        .reasoning("reasoning")
                        .addSuspectRegion(
                            VerifyListResponse.Result.SuspectRegion.builder()
                                .bbox(listOf(0L, 0L, 0L, 0L))
                                .explanation("explanation")
                                .kind("kind")
                                .page(0L)
                                .score(0.0)
                                .source("source")
                                .primary(true)
                                .review("review")
                                .build()
                        )
                        .syntheticScore(0.0)
                        .tamperingScore(0.0)
                        .build()
                )
                .transactionId("transaction_id")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(verifyListResponse.id()).isEqualTo("id")
        assertThat(verifyListResponse.configuration())
            .isEqualTo(
                VerifyListResponse.Configuration.builder()
                    .targetPages("1,3,5-7")
                    .tier(VerifyListResponse.Configuration.Tier.AGENTIC)
                    .build()
            )
        assertThat(verifyListResponse.documentInputType())
            .isEqualTo(VerifyListResponse.DocumentInputType.FILE_ID)
        assertThat(verifyListResponse.fileInput()).isEqualTo("file_input")
        assertThat(verifyListResponse.projectId()).isEqualTo("project_id")
        assertThat(verifyListResponse.status()).isEqualTo(VerifyListResponse.Status.CANCELLED)
        assertThat(verifyListResponse.userId()).isEqualTo("user_id")
        assertThat(verifyListResponse.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(verifyListResponse.errorMessage()).contains("error_message")
        assertThat(verifyListResponse.result())
            .contains(
                VerifyListResponse.Result.builder()
                    .detectorVersion("detector_version")
                    .overallScore(0.0)
                    .verdict(VerifyListResponse.Result.Verdict.AUTHENTIC)
                    .compositeScores(
                        VerifyListResponse.Result.CompositeScores.builder()
                            .aiGenerated(
                                VerifyListResponse.Result.CompositeScores.AiGenerated.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .documentCoherence(
                                VerifyListResponse.Result.CompositeScores.DocumentCoherence
                                    .builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .documentMetadata(
                                VerifyListResponse.Result.CompositeScores.DocumentMetadata.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .knownFraud(
                                VerifyListResponse.Result.CompositeScores.KnownFraud.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .manuallyEdited(
                                VerifyListResponse.Result.CompositeScores.ManuallyEdited.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .recapture(
                                VerifyListResponse.Result.CompositeScores.Recapture.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .confidence(0.0)
                    .error("error")
                    .pageCount(1L)
                    .addPageDimension(
                        VerifyListResponse.Result.PageDimension.builder()
                            .height(0L)
                            .page(0L)
                            .width(0L)
                            .build()
                    )
                    .reasoning("reasoning")
                    .addSuspectRegion(
                        VerifyListResponse.Result.SuspectRegion.builder()
                            .bbox(listOf(0L, 0L, 0L, 0L))
                            .explanation("explanation")
                            .kind("kind")
                            .page(0L)
                            .score(0.0)
                            .source("source")
                            .primary(true)
                            .review("review")
                            .build()
                    )
                    .syntheticScore(0.0)
                    .tamperingScore(0.0)
                    .build()
            )
        assertThat(verifyListResponse.transactionId()).contains("transaction_id")
        assertThat(verifyListResponse.updatedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val verifyListResponse =
            VerifyListResponse.builder()
                .id("id")
                .configuration(
                    VerifyListResponse.Configuration.builder()
                        .targetPages("1,3,5-7")
                        .tier(VerifyListResponse.Configuration.Tier.AGENTIC)
                        .build()
                )
                .documentInputType(VerifyListResponse.DocumentInputType.FILE_ID)
                .fileInput("file_input")
                .projectId("project_id")
                .status(VerifyListResponse.Status.CANCELLED)
                .userId("user_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .errorMessage("error_message")
                .result(
                    VerifyListResponse.Result.builder()
                        .detectorVersion("detector_version")
                        .overallScore(0.0)
                        .verdict(VerifyListResponse.Result.Verdict.AUTHENTIC)
                        .compositeScores(
                            VerifyListResponse.Result.CompositeScores.builder()
                                .aiGenerated(
                                    VerifyListResponse.Result.CompositeScores.AiGenerated.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentCoherence(
                                    VerifyListResponse.Result.CompositeScores.DocumentCoherence
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentMetadata(
                                    VerifyListResponse.Result.CompositeScores.DocumentMetadata
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .knownFraud(
                                    VerifyListResponse.Result.CompositeScores.KnownFraud.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .manuallyEdited(
                                    VerifyListResponse.Result.CompositeScores.ManuallyEdited
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .recapture(
                                    VerifyListResponse.Result.CompositeScores.Recapture.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .confidence(0.0)
                        .error("error")
                        .pageCount(1L)
                        .addPageDimension(
                            VerifyListResponse.Result.PageDimension.builder()
                                .height(0L)
                                .page(0L)
                                .width(0L)
                                .build()
                        )
                        .reasoning("reasoning")
                        .addSuspectRegion(
                            VerifyListResponse.Result.SuspectRegion.builder()
                                .bbox(listOf(0L, 0L, 0L, 0L))
                                .explanation("explanation")
                                .kind("kind")
                                .page(0L)
                                .score(0.0)
                                .source("source")
                                .primary(true)
                                .review("review")
                                .build()
                        )
                        .syntheticScore(0.0)
                        .tamperingScore(0.0)
                        .build()
                )
                .transactionId("transaction_id")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedVerifyListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(verifyListResponse),
                jacksonTypeRef<VerifyListResponse>(),
            )

        assertThat(roundtrippedVerifyListResponse).isEqualTo(verifyListResponse)
    }
}
