// File generated from our OpenAPI spec by Stainless.

package ai.llamaindex.llamacloud.models.alpha.verify

import ai.llamaindex.llamacloud.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class VerifyCancelResponseTest {

    @Test
    fun create() {
        val verifyCancelResponse =
            VerifyCancelResponse.builder()
                .id("id")
                .configuration(
                    VerifyCancelResponse.Configuration.builder()
                        .targetPages("1,3,5-7")
                        .tier(VerifyCancelResponse.Configuration.Tier.AGENTIC)
                        .build()
                )
                .documentInputType(VerifyCancelResponse.DocumentInputType.FILE_ID)
                .fileInput("file_input")
                .projectId("project_id")
                .status(VerifyCancelResponse.Status.CANCELLED)
                .userId("user_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .errorMessage("error_message")
                .result(
                    VerifyCancelResponse.Result.builder()
                        .detectorVersion("detector_version")
                        .overallScore(0.0)
                        .verdict(VerifyCancelResponse.Result.Verdict.AUTHENTIC)
                        .compositeScores(
                            VerifyCancelResponse.Result.CompositeScores.builder()
                                .aiGenerated(
                                    VerifyCancelResponse.Result.CompositeScores.AiGenerated
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentCoherence(
                                    VerifyCancelResponse.Result.CompositeScores.DocumentCoherence
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentMetadata(
                                    VerifyCancelResponse.Result.CompositeScores.DocumentMetadata
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .knownFraud(
                                    VerifyCancelResponse.Result.CompositeScores.KnownFraud.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .manuallyEdited(
                                    VerifyCancelResponse.Result.CompositeScores.ManuallyEdited
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .recapture(
                                    VerifyCancelResponse.Result.CompositeScores.Recapture.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .confidence(0.0)
                        .error("error")
                        .pageCount(1L)
                        .addPageDimension(
                            VerifyCancelResponse.Result.PageDimension.builder()
                                .height(0L)
                                .page(0L)
                                .width(0L)
                                .build()
                        )
                        .reasoning("reasoning")
                        .addSuspectRegion(
                            VerifyCancelResponse.Result.SuspectRegion.builder()
                                .bbox(listOf(0L, 0L, 0L, 0L))
                                .explanation("explanation")
                                .kind("kind")
                                .page(0L)
                                .score(0.0)
                                .source("source")
                                .primary(true)
                                .review("review")
                                .build()
                        )
                        .syntheticScore(0.0)
                        .tamperingScore(0.0)
                        .build()
                )
                .transactionId("transaction_id")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(verifyCancelResponse.id()).isEqualTo("id")
        assertThat(verifyCancelResponse.configuration())
            .isEqualTo(
                VerifyCancelResponse.Configuration.builder()
                    .targetPages("1,3,5-7")
                    .tier(VerifyCancelResponse.Configuration.Tier.AGENTIC)
                    .build()
            )
        assertThat(verifyCancelResponse.documentInputType())
            .isEqualTo(VerifyCancelResponse.DocumentInputType.FILE_ID)
        assertThat(verifyCancelResponse.fileInput()).isEqualTo("file_input")
        assertThat(verifyCancelResponse.projectId()).isEqualTo("project_id")
        assertThat(verifyCancelResponse.status()).isEqualTo(VerifyCancelResponse.Status.CANCELLED)
        assertThat(verifyCancelResponse.userId()).isEqualTo("user_id")
        assertThat(verifyCancelResponse.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(verifyCancelResponse.errorMessage()).contains("error_message")
        assertThat(verifyCancelResponse.result())
            .contains(
                VerifyCancelResponse.Result.builder()
                    .detectorVersion("detector_version")
                    .overallScore(0.0)
                    .verdict(VerifyCancelResponse.Result.Verdict.AUTHENTIC)
                    .compositeScores(
                        VerifyCancelResponse.Result.CompositeScores.builder()
                            .aiGenerated(
                                VerifyCancelResponse.Result.CompositeScores.AiGenerated.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .documentCoherence(
                                VerifyCancelResponse.Result.CompositeScores.DocumentCoherence
                                    .builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .documentMetadata(
                                VerifyCancelResponse.Result.CompositeScores.DocumentMetadata
                                    .builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .knownFraud(
                                VerifyCancelResponse.Result.CompositeScores.KnownFraud.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .manuallyEdited(
                                VerifyCancelResponse.Result.CompositeScores.ManuallyEdited.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .recapture(
                                VerifyCancelResponse.Result.CompositeScores.Recapture.builder()
                                    .applicable(true)
                                    .score(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .confidence(0.0)
                    .error("error")
                    .pageCount(1L)
                    .addPageDimension(
                        VerifyCancelResponse.Result.PageDimension.builder()
                            .height(0L)
                            .page(0L)
                            .width(0L)
                            .build()
                    )
                    .reasoning("reasoning")
                    .addSuspectRegion(
                        VerifyCancelResponse.Result.SuspectRegion.builder()
                            .bbox(listOf(0L, 0L, 0L, 0L))
                            .explanation("explanation")
                            .kind("kind")
                            .page(0L)
                            .score(0.0)
                            .source("source")
                            .primary(true)
                            .review("review")
                            .build()
                    )
                    .syntheticScore(0.0)
                    .tamperingScore(0.0)
                    .build()
            )
        assertThat(verifyCancelResponse.transactionId()).contains("transaction_id")
        assertThat(verifyCancelResponse.updatedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val verifyCancelResponse =
            VerifyCancelResponse.builder()
                .id("id")
                .configuration(
                    VerifyCancelResponse.Configuration.builder()
                        .targetPages("1,3,5-7")
                        .tier(VerifyCancelResponse.Configuration.Tier.AGENTIC)
                        .build()
                )
                .documentInputType(VerifyCancelResponse.DocumentInputType.FILE_ID)
                .fileInput("file_input")
                .projectId("project_id")
                .status(VerifyCancelResponse.Status.CANCELLED)
                .userId("user_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .errorMessage("error_message")
                .result(
                    VerifyCancelResponse.Result.builder()
                        .detectorVersion("detector_version")
                        .overallScore(0.0)
                        .verdict(VerifyCancelResponse.Result.Verdict.AUTHENTIC)
                        .compositeScores(
                            VerifyCancelResponse.Result.CompositeScores.builder()
                                .aiGenerated(
                                    VerifyCancelResponse.Result.CompositeScores.AiGenerated
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentCoherence(
                                    VerifyCancelResponse.Result.CompositeScores.DocumentCoherence
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .documentMetadata(
                                    VerifyCancelResponse.Result.CompositeScores.DocumentMetadata
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .knownFraud(
                                    VerifyCancelResponse.Result.CompositeScores.KnownFraud.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .manuallyEdited(
                                    VerifyCancelResponse.Result.CompositeScores.ManuallyEdited
                                        .builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .recapture(
                                    VerifyCancelResponse.Result.CompositeScores.Recapture.builder()
                                        .applicable(true)
                                        .score(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .confidence(0.0)
                        .error("error")
                        .pageCount(1L)
                        .addPageDimension(
                            VerifyCancelResponse.Result.PageDimension.builder()
                                .height(0L)
                                .page(0L)
                                .width(0L)
                                .build()
                        )
                        .reasoning("reasoning")
                        .addSuspectRegion(
                            VerifyCancelResponse.Result.SuspectRegion.builder()
                                .bbox(listOf(0L, 0L, 0L, 0L))
                                .explanation("explanation")
                                .kind("kind")
                                .page(0L)
                                .score(0.0)
                                .source("source")
                                .primary(true)
                                .review("review")
                                .build()
                        )
                        .syntheticScore(0.0)
                        .tamperingScore(0.0)
                        .build()
                )
                .transactionId("transaction_id")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedVerifyCancelResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(verifyCancelResponse),
                jacksonTypeRef<VerifyCancelResponse>(),
            )

        assertThat(roundtrippedVerifyCancelResponse).isEqualTo(verifyCancelResponse)
    }
}
