// File generated from our OpenAPI spec by Stainless.

package com.llamacloud_prod.api.models.beta.batch.jobitems

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.llamacloud_prod.api.core.JsonValue
import com.llamacloud_prod.api.core.jsonMapper
import com.llamacloud_prod.api.models.parsing.FailPageMode
import com.llamacloud_prod.api.models.parsing.ParsingLanguages
import com.llamacloud_prod.api.models.parsing.ParsingMode
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class JobItemGetProcessingResultsResponseTest {

    @Test
    fun create() {
        val jobItemGetProcessingResultsResponse =
            JobItemGetProcessingResultsResponse.builder()
                .itemId("item_id")
                .itemName("item_name")
                .addProcessingResult(
                    JobItemGetProcessingResultsResponse.ProcessingResult.builder()
                        .itemId("item_id")
                        .jobConfig(
                            JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                .BatchParseJobRecordCreate
                                .builder()
                                .correlationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .jobName(
                                    JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                        .BatchParseJobRecordCreate
                                        .JobName
                                        .PARSE_RAW_FILE_JOB
                                )
                                .parameters(
                                    JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                        .BatchParseJobRecordCreate
                                        .Parameters
                                        .builder()
                                        .adaptiveLongTable(true)
                                        .aggressiveTableExtraction(true)
                                        .annotateLinks(true)
                                        .autoMode(true)
                                        .autoModeConfigurationJson("auto_mode_configuration_json")
                                        .autoModeTriggerOnImageInPage(true)
                                        .autoModeTriggerOnRegexpInPage(
                                            "auto_mode_trigger_on_regexp_in_page"
                                        )
                                        .autoModeTriggerOnTableInPage(true)
                                        .autoModeTriggerOnTextInPage(
                                            "auto_mode_trigger_on_text_in_page"
                                        )
                                        .azureOpenAIApiVersion("azure_openai_api_version")
                                        .azureOpenAIDeploymentName("azure_openai_deployment_name")
                                        .azureOpenAIEndpoint("azure_openai_endpoint")
                                        .azureOpenAIKey("azure_openai_key")
                                        .bboxBottom(0.0)
                                        .bboxLeft(0.0)
                                        .bboxRight(0.0)
                                        .bboxTop(0.0)
                                        .boundingBox("bounding_box")
                                        .compactMarkdownTable(true)
                                        .complementalFormattingInstruction(
                                            "complemental_formatting_instruction"
                                        )
                                        .contentGuidelineInstruction(
                                            "content_guideline_instruction"
                                        )
                                        .continuousMode(true)
                                        .customMetadata(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .CustomMetadata
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .disableImageExtraction(true)
                                        .disableOcr(true)
                                        .disableReconstruction(true)
                                        .doNotCache(true)
                                        .doNotUnrollColumns(true)
                                        .enableCostOptimizer(true)
                                        .extractCharts(true)
                                        .extractLayout(true)
                                        .extractPrintedPageNumber(true)
                                        .fastMode(true)
                                        .formattingInstruction("formatting_instruction")
                                        .gpt4oApiKey("gpt4o_api_key")
                                        .gpt4oMode(true)
                                        .guessXlsxSheetName(true)
                                        .hideFooters(true)
                                        .hideHeaders(true)
                                        .highResOcr(true)
                                        .htmlMakeAllElementsVisible(true)
                                        .htmlRemoveFixedElements(true)
                                        .htmlRemoveNavigationElements(true)
                                        .httpProxy("http_proxy")
                                        .ignoreDocumentElementsForLayoutDetection(true)
                                        .addImagesToSave(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .ImagesToSave
                                                .EMBEDDED
                                        )
                                        .inlineImagesInMarkdown(true)
                                        .inputS3Path("input_s3_path")
                                        .inputS3Region("input_s3_region")
                                        .inputUrl("input_url")
                                        .internalIsScreenshotJob(true)
                                        .invalidateCache(true)
                                        .isFormattingInstruction(true)
                                        .jobTimeoutExtraTimePerPageInSeconds(0.0)
                                        .jobTimeoutInSeconds(0.0)
                                        .keepPageSeparatorWhenMergingTables(true)
                                        .lang("lang")
                                        .addLanguage(ParsingLanguages.ABQ)
                                        .layoutAware(true)
                                        .lineLevelBoundingBox(true)
                                        .markdownTableMultilineHeaderSeparator(
                                            "markdown_table_multiline_header_separator"
                                        )
                                        .maxPages(0L)
                                        .maxPagesEnforced(0L)
                                        .mergeTablesAcrossPagesInMarkdown(true)
                                        .model("model")
                                        .outlinedTableExtraction(true)
                                        .outputPdfOfDocument(true)
                                        .outputS3PathPrefix("output_s3_path_prefix")
                                        .outputS3Region("output_s3_region")
                                        .outputTablesAsHtml(true)
                                        .outputBucket("outputBucket")
                                        .pageErrorTolerance(0.0)
                                        .pageFooterPrefix("page_footer_prefix")
                                        .pageFooterSuffix("page_footer_suffix")
                                        .pageHeaderPrefix("page_header_prefix")
                                        .pageHeaderSuffix("page_header_suffix")
                                        .pagePrefix("page_prefix")
                                        .pageSeparator("page_separator")
                                        .pageSuffix("page_suffix")
                                        .parseMode(ParsingMode.PARSE_DOCUMENT_WITH_AGENT)
                                        .parsingInstruction("parsing_instruction")
                                        .pipelineId("pipeline_id")
                                        .preciseBoundingBox(true)
                                        .premiumMode(true)
                                        .presentationOutOfBoundsContent(true)
                                        .presentationSkipEmbeddedData(true)
                                        .preserveLayoutAlignmentAcrossPages(true)
                                        .preserveVerySmallText(true)
                                        .preset("preset")
                                        .priority(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .Priority
                                                .CRITICAL
                                        )
                                        .projectId("project_id")
                                        .removeHiddenText(true)
                                        .replaceFailedPageMode(FailPageMode.BLANK_PAGE)
                                        .replaceFailedPageWithErrorMessagePrefix(
                                            "replace_failed_page_with_error_message_prefix"
                                        )
                                        .replaceFailedPageWithErrorMessageSuffix(
                                            "replace_failed_page_with_error_message_suffix"
                                        )
                                        .resourceInfo(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .ResourceInfo
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .saveImages(true)
                                        .skipDiagonalText(true)
                                        .specializedChartParsingAgentic(true)
                                        .specializedChartParsingEfficient(true)
                                        .specializedChartParsingPlus(true)
                                        .specializedImageParsing(true)
                                        .spreadsheetExtractSubTables(true)
                                        .spreadsheetForceFormulaComputation(true)
                                        .spreadsheetIncludeHiddenSheets(true)
                                        .strictModeBuggyFont(true)
                                        .strictModeImageExtraction(true)
                                        .strictModeImageOcr(true)
                                        .strictModeReconstruction(true)
                                        .structuredOutput(true)
                                        .structuredOutputJsonSchema("structured_output_json_schema")
                                        .structuredOutputJsonSchemaName(
                                            "structured_output_json_schema_name"
                                        )
                                        .systemPrompt("system_prompt")
                                        .systemPromptAppend("system_prompt_append")
                                        .takeScreenshot(true)
                                        .targetPages("target_pages")
                                        .tier("tier")
                                        .type(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .Type
                                                .PARSE
                                        )
                                        .useVendorMultimodalModel(true)
                                        .userPrompt("user_prompt")
                                        .vendorMultimodalApiKey("vendor_multimodal_api_key")
                                        .vendorMultimodalModelName("vendor_multimodal_model_name")
                                        .version("version")
                                        .addWebhookConfiguration(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .WebhookConfiguration
                                                .builder()
                                                .addWebhookEvent(
                                                    JobItemGetProcessingResultsResponse
                                                        .ProcessingResult
                                                        .JobConfig
                                                        .BatchParseJobRecordCreate
                                                        .Parameters
                                                        .WebhookConfiguration
                                                        .WebhookEvent
                                                        .PARSE_SUCCESS
                                                )
                                                .addWebhookEvent(
                                                    JobItemGetProcessingResultsResponse
                                                        .ProcessingResult
                                                        .JobConfig
                                                        .BatchParseJobRecordCreate
                                                        .Parameters
                                                        .WebhookConfiguration
                                                        .WebhookEvent
                                                        .PARSE_ERROR
                                                )
                                                .webhookHeaders(
                                                    JobItemGetProcessingResultsResponse
                                                        .ProcessingResult
                                                        .JobConfig
                                                        .BatchParseJobRecordCreate
                                                        .Parameters
                                                        .WebhookConfiguration
                                                        .WebhookHeaders
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "Authorization",
                                                            JsonValue.from("Bearer sk-..."),
                                                        )
                                                        .build()
                                                )
                                                .webhookOutputFormat("json")
                                                .webhookSigningSecret("whsec_...")
                                                .webhookUrl(
                                                    "https://example.com/webhooks/llamacloud"
                                                )
                                                .build()
                                        )
                                        .webhookUrl("webhook_url")
                                        .build()
                                )
                                .parentJobExecutionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .partitions(
                                    JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                        .BatchParseJobRecordCreate
                                        .Partitions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"),
                                        )
                                        .build()
                                )
                                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .userId("user_id")
                                .webhookUrl("webhook_url")
                                .build()
                        )
                        .jobType(
                            JobItemGetProcessingResultsResponse.ProcessingResult.JobType.CLASSIFY
                        )
                        .outputS3Path("output_s3_path")
                        .parametersHash("parameters_hash")
                        .processedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .resultId("result_id")
                        .outputMetadata(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .build()

        assertThat(jobItemGetProcessingResultsResponse.itemId()).isEqualTo("item_id")
        assertThat(jobItemGetProcessingResultsResponse.itemName()).isEqualTo("item_name")
        assertThat(jobItemGetProcessingResultsResponse.processingResults().getOrNull())
            .containsExactly(
                JobItemGetProcessingResultsResponse.ProcessingResult.builder()
                    .itemId("item_id")
                    .jobConfig(
                        JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                            .BatchParseJobRecordCreate
                            .builder()
                            .correlationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .jobName(
                                JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                    .BatchParseJobRecordCreate
                                    .JobName
                                    .PARSE_RAW_FILE_JOB
                            )
                            .parameters(
                                JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                    .BatchParseJobRecordCreate
                                    .Parameters
                                    .builder()
                                    .adaptiveLongTable(true)
                                    .aggressiveTableExtraction(true)
                                    .annotateLinks(true)
                                    .autoMode(true)
                                    .autoModeConfigurationJson("auto_mode_configuration_json")
                                    .autoModeTriggerOnImageInPage(true)
                                    .autoModeTriggerOnRegexpInPage(
                                        "auto_mode_trigger_on_regexp_in_page"
                                    )
                                    .autoModeTriggerOnTableInPage(true)
                                    .autoModeTriggerOnTextInPage(
                                        "auto_mode_trigger_on_text_in_page"
                                    )
                                    .azureOpenAIApiVersion("azure_openai_api_version")
                                    .azureOpenAIDeploymentName("azure_openai_deployment_name")
                                    .azureOpenAIEndpoint("azure_openai_endpoint")
                                    .azureOpenAIKey("azure_openai_key")
                                    .bboxBottom(0.0)
                                    .bboxLeft(0.0)
                                    .bboxRight(0.0)
                                    .bboxTop(0.0)
                                    .boundingBox("bounding_box")
                                    .compactMarkdownTable(true)
                                    .complementalFormattingInstruction(
                                        "complemental_formatting_instruction"
                                    )
                                    .contentGuidelineInstruction("content_guideline_instruction")
                                    .continuousMode(true)
                                    .customMetadata(
                                        JobItemGetProcessingResultsResponse.ProcessingResult
                                            .JobConfig
                                            .BatchParseJobRecordCreate
                                            .Parameters
                                            .CustomMetadata
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .disableImageExtraction(true)
                                    .disableOcr(true)
                                    .disableReconstruction(true)
                                    .doNotCache(true)
                                    .doNotUnrollColumns(true)
                                    .enableCostOptimizer(true)
                                    .extractCharts(true)
                                    .extractLayout(true)
                                    .extractPrintedPageNumber(true)
                                    .fastMode(true)
                                    .formattingInstruction("formatting_instruction")
                                    .gpt4oApiKey("gpt4o_api_key")
                                    .gpt4oMode(true)
                                    .guessXlsxSheetName(true)
                                    .hideFooters(true)
                                    .hideHeaders(true)
                                    .highResOcr(true)
                                    .htmlMakeAllElementsVisible(true)
                                    .htmlRemoveFixedElements(true)
                                    .htmlRemoveNavigationElements(true)
                                    .httpProxy("http_proxy")
                                    .ignoreDocumentElementsForLayoutDetection(true)
                                    .addImagesToSave(
                                        JobItemGetProcessingResultsResponse.ProcessingResult
                                            .JobConfig
                                            .BatchParseJobRecordCreate
                                            .Parameters
                                            .ImagesToSave
                                            .EMBEDDED
                                    )
                                    .inlineImagesInMarkdown(true)
                                    .inputS3Path("input_s3_path")
                                    .inputS3Region("input_s3_region")
                                    .inputUrl("input_url")
                                    .internalIsScreenshotJob(true)
                                    .invalidateCache(true)
                                    .isFormattingInstruction(true)
                                    .jobTimeoutExtraTimePerPageInSeconds(0.0)
                                    .jobTimeoutInSeconds(0.0)
                                    .keepPageSeparatorWhenMergingTables(true)
                                    .lang("lang")
                                    .addLanguage(ParsingLanguages.ABQ)
                                    .layoutAware(true)
                                    .lineLevelBoundingBox(true)
                                    .markdownTableMultilineHeaderSeparator(
                                        "markdown_table_multiline_header_separator"
                                    )
                                    .maxPages(0L)
                                    .maxPagesEnforced(0L)
                                    .mergeTablesAcrossPagesInMarkdown(true)
                                    .model("model")
                                    .outlinedTableExtraction(true)
                                    .outputPdfOfDocument(true)
                                    .outputS3PathPrefix("output_s3_path_prefix")
                                    .outputS3Region("output_s3_region")
                                    .outputTablesAsHtml(true)
                                    .outputBucket("outputBucket")
                                    .pageErrorTolerance(0.0)
                                    .pageFooterPrefix("page_footer_prefix")
                                    .pageFooterSuffix("page_footer_suffix")
                                    .pageHeaderPrefix("page_header_prefix")
                                    .pageHeaderSuffix("page_header_suffix")
                                    .pagePrefix("page_prefix")
                                    .pageSeparator("page_separator")
                                    .pageSuffix("page_suffix")
                                    .parseMode(ParsingMode.PARSE_DOCUMENT_WITH_AGENT)
                                    .parsingInstruction("parsing_instruction")
                                    .pipelineId("pipeline_id")
                                    .preciseBoundingBox(true)
                                    .premiumMode(true)
                                    .presentationOutOfBoundsContent(true)
                                    .presentationSkipEmbeddedData(true)
                                    .preserveLayoutAlignmentAcrossPages(true)
                                    .preserveVerySmallText(true)
                                    .preset("preset")
                                    .priority(
                                        JobItemGetProcessingResultsResponse.ProcessingResult
                                            .JobConfig
                                            .BatchParseJobRecordCreate
                                            .Parameters
                                            .Priority
                                            .CRITICAL
                                    )
                                    .projectId("project_id")
                                    .removeHiddenText(true)
                                    .replaceFailedPageMode(FailPageMode.BLANK_PAGE)
                                    .replaceFailedPageWithErrorMessagePrefix(
                                        "replace_failed_page_with_error_message_prefix"
                                    )
                                    .replaceFailedPageWithErrorMessageSuffix(
                                        "replace_failed_page_with_error_message_suffix"
                                    )
                                    .resourceInfo(
                                        JobItemGetProcessingResultsResponse.ProcessingResult
                                            .JobConfig
                                            .BatchParseJobRecordCreate
                                            .Parameters
                                            .ResourceInfo
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .saveImages(true)
                                    .skipDiagonalText(true)
                                    .specializedChartParsingAgentic(true)
                                    .specializedChartParsingEfficient(true)
                                    .specializedChartParsingPlus(true)
                                    .specializedImageParsing(true)
                                    .spreadsheetExtractSubTables(true)
                                    .spreadsheetForceFormulaComputation(true)
                                    .spreadsheetIncludeHiddenSheets(true)
                                    .strictModeBuggyFont(true)
                                    .strictModeImageExtraction(true)
                                    .strictModeImageOcr(true)
                                    .strictModeReconstruction(true)
                                    .structuredOutput(true)
                                    .structuredOutputJsonSchema("structured_output_json_schema")
                                    .structuredOutputJsonSchemaName(
                                        "structured_output_json_schema_name"
                                    )
                                    .systemPrompt("system_prompt")
                                    .systemPromptAppend("system_prompt_append")
                                    .takeScreenshot(true)
                                    .targetPages("target_pages")
                                    .tier("tier")
                                    .type(
                                        JobItemGetProcessingResultsResponse.ProcessingResult
                                            .JobConfig
                                            .BatchParseJobRecordCreate
                                            .Parameters
                                            .Type
                                            .PARSE
                                    )
                                    .useVendorMultimodalModel(true)
                                    .userPrompt("user_prompt")
                                    .vendorMultimodalApiKey("vendor_multimodal_api_key")
                                    .vendorMultimodalModelName("vendor_multimodal_model_name")
                                    .version("version")
                                    .addWebhookConfiguration(
                                        JobItemGetProcessingResultsResponse.ProcessingResult
                                            .JobConfig
                                            .BatchParseJobRecordCreate
                                            .Parameters
                                            .WebhookConfiguration
                                            .builder()
                                            .addWebhookEvent(
                                                JobItemGetProcessingResultsResponse.ProcessingResult
                                                    .JobConfig
                                                    .BatchParseJobRecordCreate
                                                    .Parameters
                                                    .WebhookConfiguration
                                                    .WebhookEvent
                                                    .PARSE_SUCCESS
                                            )
                                            .addWebhookEvent(
                                                JobItemGetProcessingResultsResponse.ProcessingResult
                                                    .JobConfig
                                                    .BatchParseJobRecordCreate
                                                    .Parameters
                                                    .WebhookConfiguration
                                                    .WebhookEvent
                                                    .PARSE_ERROR
                                            )
                                            .webhookHeaders(
                                                JobItemGetProcessingResultsResponse.ProcessingResult
                                                    .JobConfig
                                                    .BatchParseJobRecordCreate
                                                    .Parameters
                                                    .WebhookConfiguration
                                                    .WebhookHeaders
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "Authorization",
                                                        JsonValue.from("Bearer sk-..."),
                                                    )
                                                    .build()
                                            )
                                            .webhookOutputFormat("json")
                                            .webhookSigningSecret("whsec_...")
                                            .webhookUrl("https://example.com/webhooks/llamacloud")
                                            .build()
                                    )
                                    .webhookUrl("webhook_url")
                                    .build()
                            )
                            .parentJobExecutionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .partitions(
                                JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                    .BatchParseJobRecordCreate
                                    .Partitions
                                    .builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"),
                                    )
                                    .build()
                            )
                            .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .userId("user_id")
                            .webhookUrl("webhook_url")
                            .build()
                    )
                    .jobType(JobItemGetProcessingResultsResponse.ProcessingResult.JobType.CLASSIFY)
                    .outputS3Path("output_s3_path")
                    .parametersHash("parameters_hash")
                    .processedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .resultId("result_id")
                    .outputMetadata(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val jobItemGetProcessingResultsResponse =
            JobItemGetProcessingResultsResponse.builder()
                .itemId("item_id")
                .itemName("item_name")
                .addProcessingResult(
                    JobItemGetProcessingResultsResponse.ProcessingResult.builder()
                        .itemId("item_id")
                        .jobConfig(
                            JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                .BatchParseJobRecordCreate
                                .builder()
                                .correlationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .jobName(
                                    JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                        .BatchParseJobRecordCreate
                                        .JobName
                                        .PARSE_RAW_FILE_JOB
                                )
                                .parameters(
                                    JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                        .BatchParseJobRecordCreate
                                        .Parameters
                                        .builder()
                                        .adaptiveLongTable(true)
                                        .aggressiveTableExtraction(true)
                                        .annotateLinks(true)
                                        .autoMode(true)
                                        .autoModeConfigurationJson("auto_mode_configuration_json")
                                        .autoModeTriggerOnImageInPage(true)
                                        .autoModeTriggerOnRegexpInPage(
                                            "auto_mode_trigger_on_regexp_in_page"
                                        )
                                        .autoModeTriggerOnTableInPage(true)
                                        .autoModeTriggerOnTextInPage(
                                            "auto_mode_trigger_on_text_in_page"
                                        )
                                        .azureOpenAIApiVersion("azure_openai_api_version")
                                        .azureOpenAIDeploymentName("azure_openai_deployment_name")
                                        .azureOpenAIEndpoint("azure_openai_endpoint")
                                        .azureOpenAIKey("azure_openai_key")
                                        .bboxBottom(0.0)
                                        .bboxLeft(0.0)
                                        .bboxRight(0.0)
                                        .bboxTop(0.0)
                                        .boundingBox("bounding_box")
                                        .compactMarkdownTable(true)
                                        .complementalFormattingInstruction(
                                            "complemental_formatting_instruction"
                                        )
                                        .contentGuidelineInstruction(
                                            "content_guideline_instruction"
                                        )
                                        .continuousMode(true)
                                        .customMetadata(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .CustomMetadata
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .disableImageExtraction(true)
                                        .disableOcr(true)
                                        .disableReconstruction(true)
                                        .doNotCache(true)
                                        .doNotUnrollColumns(true)
                                        .enableCostOptimizer(true)
                                        .extractCharts(true)
                                        .extractLayout(true)
                                        .extractPrintedPageNumber(true)
                                        .fastMode(true)
                                        .formattingInstruction("formatting_instruction")
                                        .gpt4oApiKey("gpt4o_api_key")
                                        .gpt4oMode(true)
                                        .guessXlsxSheetName(true)
                                        .hideFooters(true)
                                        .hideHeaders(true)
                                        .highResOcr(true)
                                        .htmlMakeAllElementsVisible(true)
                                        .htmlRemoveFixedElements(true)
                                        .htmlRemoveNavigationElements(true)
                                        .httpProxy("http_proxy")
                                        .ignoreDocumentElementsForLayoutDetection(true)
                                        .addImagesToSave(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .ImagesToSave
                                                .EMBEDDED
                                        )
                                        .inlineImagesInMarkdown(true)
                                        .inputS3Path("input_s3_path")
                                        .inputS3Region("input_s3_region")
                                        .inputUrl("input_url")
                                        .internalIsScreenshotJob(true)
                                        .invalidateCache(true)
                                        .isFormattingInstruction(true)
                                        .jobTimeoutExtraTimePerPageInSeconds(0.0)
                                        .jobTimeoutInSeconds(0.0)
                                        .keepPageSeparatorWhenMergingTables(true)
                                        .lang("lang")
                                        .addLanguage(ParsingLanguages.ABQ)
                                        .layoutAware(true)
                                        .lineLevelBoundingBox(true)
                                        .markdownTableMultilineHeaderSeparator(
                                            "markdown_table_multiline_header_separator"
                                        )
                                        .maxPages(0L)
                                        .maxPagesEnforced(0L)
                                        .mergeTablesAcrossPagesInMarkdown(true)
                                        .model("model")
                                        .outlinedTableExtraction(true)
                                        .outputPdfOfDocument(true)
                                        .outputS3PathPrefix("output_s3_path_prefix")
                                        .outputS3Region("output_s3_region")
                                        .outputTablesAsHtml(true)
                                        .outputBucket("outputBucket")
                                        .pageErrorTolerance(0.0)
                                        .pageFooterPrefix("page_footer_prefix")
                                        .pageFooterSuffix("page_footer_suffix")
                                        .pageHeaderPrefix("page_header_prefix")
                                        .pageHeaderSuffix("page_header_suffix")
                                        .pagePrefix("page_prefix")
                                        .pageSeparator("page_separator")
                                        .pageSuffix("page_suffix")
                                        .parseMode(ParsingMode.PARSE_DOCUMENT_WITH_AGENT)
                                        .parsingInstruction("parsing_instruction")
                                        .pipelineId("pipeline_id")
                                        .preciseBoundingBox(true)
                                        .premiumMode(true)
                                        .presentationOutOfBoundsContent(true)
                                        .presentationSkipEmbeddedData(true)
                                        .preserveLayoutAlignmentAcrossPages(true)
                                        .preserveVerySmallText(true)
                                        .preset("preset")
                                        .priority(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .Priority
                                                .CRITICAL
                                        )
                                        .projectId("project_id")
                                        .removeHiddenText(true)
                                        .replaceFailedPageMode(FailPageMode.BLANK_PAGE)
                                        .replaceFailedPageWithErrorMessagePrefix(
                                            "replace_failed_page_with_error_message_prefix"
                                        )
                                        .replaceFailedPageWithErrorMessageSuffix(
                                            "replace_failed_page_with_error_message_suffix"
                                        )
                                        .resourceInfo(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .ResourceInfo
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .saveImages(true)
                                        .skipDiagonalText(true)
                                        .specializedChartParsingAgentic(true)
                                        .specializedChartParsingEfficient(true)
                                        .specializedChartParsingPlus(true)
                                        .specializedImageParsing(true)
                                        .spreadsheetExtractSubTables(true)
                                        .spreadsheetForceFormulaComputation(true)
                                        .spreadsheetIncludeHiddenSheets(true)
                                        .strictModeBuggyFont(true)
                                        .strictModeImageExtraction(true)
                                        .strictModeImageOcr(true)
                                        .strictModeReconstruction(true)
                                        .structuredOutput(true)
                                        .structuredOutputJsonSchema("structured_output_json_schema")
                                        .structuredOutputJsonSchemaName(
                                            "structured_output_json_schema_name"
                                        )
                                        .systemPrompt("system_prompt")
                                        .systemPromptAppend("system_prompt_append")
                                        .takeScreenshot(true)
                                        .targetPages("target_pages")
                                        .tier("tier")
                                        .type(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .Type
                                                .PARSE
                                        )
                                        .useVendorMultimodalModel(true)
                                        .userPrompt("user_prompt")
                                        .vendorMultimodalApiKey("vendor_multimodal_api_key")
                                        .vendorMultimodalModelName("vendor_multimodal_model_name")
                                        .version("version")
                                        .addWebhookConfiguration(
                                            JobItemGetProcessingResultsResponse.ProcessingResult
                                                .JobConfig
                                                .BatchParseJobRecordCreate
                                                .Parameters
                                                .WebhookConfiguration
                                                .builder()
                                                .addWebhookEvent(
                                                    JobItemGetProcessingResultsResponse
                                                        .ProcessingResult
                                                        .JobConfig
                                                        .BatchParseJobRecordCreate
                                                        .Parameters
                                                        .WebhookConfiguration
                                                        .WebhookEvent
                                                        .PARSE_SUCCESS
                                                )
                                                .addWebhookEvent(
                                                    JobItemGetProcessingResultsResponse
                                                        .ProcessingResult
                                                        .JobConfig
                                                        .BatchParseJobRecordCreate
                                                        .Parameters
                                                        .WebhookConfiguration
                                                        .WebhookEvent
                                                        .PARSE_ERROR
                                                )
                                                .webhookHeaders(
                                                    JobItemGetProcessingResultsResponse
                                                        .ProcessingResult
                                                        .JobConfig
                                                        .BatchParseJobRecordCreate
                                                        .Parameters
                                                        .WebhookConfiguration
                                                        .WebhookHeaders
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "Authorization",
                                                            JsonValue.from("Bearer sk-..."),
                                                        )
                                                        .build()
                                                )
                                                .webhookOutputFormat("json")
                                                .webhookSigningSecret("whsec_...")
                                                .webhookUrl(
                                                    "https://example.com/webhooks/llamacloud"
                                                )
                                                .build()
                                        )
                                        .webhookUrl("webhook_url")
                                        .build()
                                )
                                .parentJobExecutionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .partitions(
                                    JobItemGetProcessingResultsResponse.ProcessingResult.JobConfig
                                        .BatchParseJobRecordCreate
                                        .Partitions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"),
                                        )
                                        .build()
                                )
                                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .sessionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .userId("user_id")
                                .webhookUrl("webhook_url")
                                .build()
                        )
                        .jobType(
                            JobItemGetProcessingResultsResponse.ProcessingResult.JobType.CLASSIFY
                        )
                        .outputS3Path("output_s3_path")
                        .parametersHash("parameters_hash")
                        .processedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .resultId("result_id")
                        .outputMetadata(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .build()

        val roundtrippedJobItemGetProcessingResultsResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(jobItemGetProcessingResultsResponse),
                jacksonTypeRef<JobItemGetProcessingResultsResponse>(),
            )

        assertThat(roundtrippedJobItemGetProcessingResultsResponse)
            .isEqualTo(jobItemGetProcessingResultsResponse)
    }
}
