// File generated from our OpenAPI spec by Stainless.

package ai.llamaindex.llamacloud.models.parsing

import ai.llamaindex.llamacloud.core.JsonValue
import ai.llamaindex.llamacloud.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class FormTextTest {

    @Test
    fun create() {
        val formText =
            FormText.builder()
                .value("value")
                .addBbox(
                    BBox.builder()
                        .h(0.0)
                        .w(0.0)
                        .x(0.0)
                        .y(0.0)
                        .confidence(0.0)
                        .endIndex(0L)
                        .label("label")
                        .r(0.0)
                        .startIndex(0L)
                        .build()
                )
                .grounding(
                    FormText.Grounding.builder()
                        .id(
                            FormText.Grounding.Id.builder()
                                .addLine(
                                    FormText.Grounding.Id.Line.builder()
                                        .bbox(
                                            BBox.builder()
                                                .h(0.0)
                                                .w(0.0)
                                                .x(0.0)
                                                .y(0.0)
                                                .confidence(0.0)
                                                .endIndex(0L)
                                                .label("label")
                                                .r(0.0)
                                                .startIndex(0L)
                                                .build()
                                        )
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addWord(
                                            FormText.Grounding.Id.Line.Word.builder()
                                                .bbox(
                                                    BBox.builder()
                                                        .h(0.0)
                                                        .w(0.0)
                                                        .x(0.0)
                                                        .y(0.0)
                                                        .confidence(0.0)
                                                        .endIndex(0L)
                                                        .label("label")
                                                        .r(0.0)
                                                        .startIndex(0L)
                                                        .build()
                                                )
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .label(
                            FormText.Grounding.Label.builder()
                                .addLine(
                                    FormText.Grounding.Label.Line.builder()
                                        .bbox(
                                            BBox.builder()
                                                .h(0.0)
                                                .w(0.0)
                                                .x(0.0)
                                                .y(0.0)
                                                .confidence(0.0)
                                                .endIndex(0L)
                                                .label("label")
                                                .r(0.0)
                                                .startIndex(0L)
                                                .build()
                                        )
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addWord(
                                            FormText.Grounding.Label.Line.Word.builder()
                                                .bbox(
                                                    BBox.builder()
                                                        .h(0.0)
                                                        .w(0.0)
                                                        .x(0.0)
                                                        .y(0.0)
                                                        .confidence(0.0)
                                                        .endIndex(0L)
                                                        .label("label")
                                                        .r(0.0)
                                                        .startIndex(0L)
                                                        .build()
                                                )
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .value(
                            FormText.Grounding.Value.builder()
                                .addLine(
                                    FormText.Grounding.Value.Line.builder()
                                        .bbox(
                                            BBox.builder()
                                                .h(0.0)
                                                .w(0.0)
                                                .x(0.0)
                                                .y(0.0)
                                                .confidence(0.0)
                                                .endIndex(0L)
                                                .label("label")
                                                .r(0.0)
                                                .startIndex(0L)
                                                .build()
                                        )
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addWord(
                                            FormText.Grounding.Value.Line.Word.builder()
                                                .bbox(
                                                    BBox.builder()
                                                        .h(0.0)
                                                        .w(0.0)
                                                        .x(0.0)
                                                        .y(0.0)
                                                        .confidence(0.0)
                                                        .endIndex(0L)
                                                        .label("label")
                                                        .r(0.0)
                                                        .startIndex(0L)
                                                        .build()
                                                )
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .type(FormText.Type.TEXT)
                .build()

        assertThat(formText.value()).isEqualTo("value")
        assertThat(formText.bbox().getOrNull())
            .containsExactly(
                BBox.builder()
                    .h(0.0)
                    .w(0.0)
                    .x(0.0)
                    .y(0.0)
                    .confidence(0.0)
                    .endIndex(0L)
                    .label("label")
                    .r(0.0)
                    .startIndex(0L)
                    .build()
            )
        assertThat(formText.grounding())
            .contains(
                FormText.Grounding.builder()
                    .id(
                        FormText.Grounding.Id.builder()
                            .addLine(
                                FormText.Grounding.Id.Line.builder()
                                    .bbox(
                                        BBox.builder()
                                            .h(0.0)
                                            .w(0.0)
                                            .x(0.0)
                                            .y(0.0)
                                            .confidence(0.0)
                                            .endIndex(0L)
                                            .label("label")
                                            .r(0.0)
                                            .startIndex(0L)
                                            .build()
                                    )
                                    .addSpan(JsonValue.from(mapOf<String, Any>()))
                                    .addSpan(JsonValue.from(mapOf<String, Any>()))
                                    .addWord(
                                        FormText.Grounding.Id.Line.Word.builder()
                                            .bbox(
                                                BBox.builder()
                                                    .h(0.0)
                                                    .w(0.0)
                                                    .x(0.0)
                                                    .y(0.0)
                                                    .confidence(0.0)
                                                    .endIndex(0L)
                                                    .label("label")
                                                    .r(0.0)
                                                    .startIndex(0L)
                                                    .build()
                                            )
                                            .addSpan(JsonValue.from(mapOf<String, Any>()))
                                            .addSpan(JsonValue.from(mapOf<String, Any>()))
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .label(
                        FormText.Grounding.Label.builder()
                            .addLine(
                                FormText.Grounding.Label.Line.builder()
                                    .bbox(
                                        BBox.builder()
                                            .h(0.0)
                                            .w(0.0)
                                            .x(0.0)
                                            .y(0.0)
                                            .confidence(0.0)
                                            .endIndex(0L)
                                            .label("label")
                                            .r(0.0)
                                            .startIndex(0L)
                                            .build()
                                    )
                                    .addSpan(JsonValue.from(mapOf<String, Any>()))
                                    .addSpan(JsonValue.from(mapOf<String, Any>()))
                                    .addWord(
                                        FormText.Grounding.Label.Line.Word.builder()
                                            .bbox(
                                                BBox.builder()
                                                    .h(0.0)
                                                    .w(0.0)
                                                    .x(0.0)
                                                    .y(0.0)
                                                    .confidence(0.0)
                                                    .endIndex(0L)
                                                    .label("label")
                                                    .r(0.0)
                                                    .startIndex(0L)
                                                    .build()
                                            )
                                            .addSpan(JsonValue.from(mapOf<String, Any>()))
                                            .addSpan(JsonValue.from(mapOf<String, Any>()))
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .value(
                        FormText.Grounding.Value.builder()
                            .addLine(
                                FormText.Grounding.Value.Line.builder()
                                    .bbox(
                                        BBox.builder()
                                            .h(0.0)
                                            .w(0.0)
                                            .x(0.0)
                                            .y(0.0)
                                            .confidence(0.0)
                                            .endIndex(0L)
                                            .label("label")
                                            .r(0.0)
                                            .startIndex(0L)
                                            .build()
                                    )
                                    .addSpan(JsonValue.from(mapOf<String, Any>()))
                                    .addSpan(JsonValue.from(mapOf<String, Any>()))
                                    .addWord(
                                        FormText.Grounding.Value.Line.Word.builder()
                                            .bbox(
                                                BBox.builder()
                                                    .h(0.0)
                                                    .w(0.0)
                                                    .x(0.0)
                                                    .y(0.0)
                                                    .confidence(0.0)
                                                    .endIndex(0L)
                                                    .label("label")
                                                    .r(0.0)
                                                    .startIndex(0L)
                                                    .build()
                                            )
                                            .addSpan(JsonValue.from(mapOf<String, Any>()))
                                            .addSpan(JsonValue.from(mapOf<String, Any>()))
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(formText.type()).contains(FormText.Type.TEXT)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val formText =
            FormText.builder()
                .value("value")
                .addBbox(
                    BBox.builder()
                        .h(0.0)
                        .w(0.0)
                        .x(0.0)
                        .y(0.0)
                        .confidence(0.0)
                        .endIndex(0L)
                        .label("label")
                        .r(0.0)
                        .startIndex(0L)
                        .build()
                )
                .grounding(
                    FormText.Grounding.builder()
                        .id(
                            FormText.Grounding.Id.builder()
                                .addLine(
                                    FormText.Grounding.Id.Line.builder()
                                        .bbox(
                                            BBox.builder()
                                                .h(0.0)
                                                .w(0.0)
                                                .x(0.0)
                                                .y(0.0)
                                                .confidence(0.0)
                                                .endIndex(0L)
                                                .label("label")
                                                .r(0.0)
                                                .startIndex(0L)
                                                .build()
                                        )
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addWord(
                                            FormText.Grounding.Id.Line.Word.builder()
                                                .bbox(
                                                    BBox.builder()
                                                        .h(0.0)
                                                        .w(0.0)
                                                        .x(0.0)
                                                        .y(0.0)
                                                        .confidence(0.0)
                                                        .endIndex(0L)
                                                        .label("label")
                                                        .r(0.0)
                                                        .startIndex(0L)
                                                        .build()
                                                )
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .label(
                            FormText.Grounding.Label.builder()
                                .addLine(
                                    FormText.Grounding.Label.Line.builder()
                                        .bbox(
                                            BBox.builder()
                                                .h(0.0)
                                                .w(0.0)
                                                .x(0.0)
                                                .y(0.0)
                                                .confidence(0.0)
                                                .endIndex(0L)
                                                .label("label")
                                                .r(0.0)
                                                .startIndex(0L)
                                                .build()
                                        )
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addWord(
                                            FormText.Grounding.Label.Line.Word.builder()
                                                .bbox(
                                                    BBox.builder()
                                                        .h(0.0)
                                                        .w(0.0)
                                                        .x(0.0)
                                                        .y(0.0)
                                                        .confidence(0.0)
                                                        .endIndex(0L)
                                                        .label("label")
                                                        .r(0.0)
                                                        .startIndex(0L)
                                                        .build()
                                                )
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .value(
                            FormText.Grounding.Value.builder()
                                .addLine(
                                    FormText.Grounding.Value.Line.builder()
                                        .bbox(
                                            BBox.builder()
                                                .h(0.0)
                                                .w(0.0)
                                                .x(0.0)
                                                .y(0.0)
                                                .confidence(0.0)
                                                .endIndex(0L)
                                                .label("label")
                                                .r(0.0)
                                                .startIndex(0L)
                                                .build()
                                        )
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addSpan(JsonValue.from(mapOf<String, Any>()))
                                        .addWord(
                                            FormText.Grounding.Value.Line.Word.builder()
                                                .bbox(
                                                    BBox.builder()
                                                        .h(0.0)
                                                        .w(0.0)
                                                        .x(0.0)
                                                        .y(0.0)
                                                        .confidence(0.0)
                                                        .endIndex(0L)
                                                        .label("label")
                                                        .r(0.0)
                                                        .startIndex(0L)
                                                        .build()
                                                )
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .addSpan(JsonValue.from(mapOf<String, Any>()))
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .type(FormText.Type.TEXT)
                .build()

        val roundtrippedFormText =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(formText),
                jacksonTypeRef<FormText>(),
            )

        assertThat(roundtrippedFormText).isEqualTo(formText)
    }
}
